service: serverless-auth0-authorizer
frameworkVersion: '2 || 3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  lambdaHashingVersion: '20201221'
  region: 'us-east-1'
  environment:
    AUTH0_PUBLIC_KEY: ${file(secret.pem)}
  httpApi:
    cors: true
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizer-function

functions:
  public-endpoint:
    handler: src/handlers/public.handler
    events:
      - httpApi:
          path: '/public'
          method: POST

  private-endpoint:
    handler: src/handlers/private.handler
    events:
      - httpApi:
          path: '/private'
          method: POST
          authorizer:
            name: customAuthorizer

  authorizer-function:
    handler: src/handlers/auth.handler

custom:
  bundle:
    linting: false
